# Generated by Django 3.0.7 on 2026-04-09 20:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workshop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0016_auto_20260407_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='attachmentfile',
            name='attachments',
            field=models.FileField(help_text='Upload workshop documents like schedule or instructions.', upload_to=workshop_app.models.attachments),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('computer engineering', 'Computer Science'), ('information technology', 'Information Technology'), ('civil engineering', 'Civil Engineering'), ('electrical engineering', 'Electrical Engineering'), ('mechanical engineering', 'Mechanical Engineering'), ('chemical engineering', 'Chemical Engineering'), ('aerospace engineering', 'Aerospace Engineering'), ('biosciences and bioengineering', 'Biosciences and BioEngineering'), ('electronics', 'Electronics'), ('energy science and engineering', 'Energy Science and Engineering')], max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 10 digits allowed.", regex='^.{10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('instructor', 'Instructor')], default='coordinator', help_text='Select Coordinator if you want to organise a workshop in your college/school. Select Instructor if you want to conduct a workshop.', max_length=32),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tnc_accepted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_app.WorkshopType'),
        ),
    ]
